//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calanthe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalantheEntities : DbContext
    {
        private static CalantheEntities _context;
      
        public CalantheEntities()
            : base("name=CalantheEntities")
        {
        }

        public static CalantheEntities GetContext()
        {
            if (_context == null)
            {
                _context = new CalantheEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<PracticalLesson> PracticalLesson { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TheoreticalLesson> TheoreticalLesson { get; set; }
        public virtual DbSet<Vocabulary> Vocabulary { get; set; }
    }
}
